### ISSUE TITLE
文章无法折叠

### ISSUE THREAD

**Issue by TianruiShi** [korilin/hexo-theme-particle#3]
文章无法折叠．
虽然底下显示＂阅读全文＂了，但实际上预览的部分内容就是全部的内容

**Comment by korilin** [comment]
主题的文章折叠是使用Hexo摘要的方式，Hexo会将md文档中 之前的部分提取出来作为摘要，如果文章没有这一个注释将无法提取出摘要，这种情况默认会显示文章所有内容。
