### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Wu-yikun** [korilin/hexo-theme-particle#4]
**请问如何限制展示字数，以点击 "阅读更多" 呢？**

我的首页都是整篇文章展示的...

![image](https://user-images.githubusercontent.com/66561334/130212945-02860572-ffcf-4a8e-a859-9d4be529c0a2.png)

**Comment by korilin** [comment]
在你的文章那里，需要省略的内容前面插入 `<!-- more -->` ，如下：

```markdown

要显示的内容
OAuth 是用于......

<!-- more -->

要隐藏的内容

```

**Comment by Wu-yikun** [comment]
> 在你的文章那里，需要省略的内容前面插入 `<!-- more -->` ，如下：
> 
> ```gfm
> 要显示的内容
> OAuth 是用于......
> 
> 
> 
> 要隐藏的内容
> ```
> 
> 这在文档里面会成为一个注释，不会影响到你把文章迁移到其它地方。
> Hexo 会把前面的内容单独抽出来，记得 more 两边最好都有一个空格。
> 
> 如果还没能解决你可以重新打开这个 issue

那每一篇文章都需要如此设置吗？请问下有**全局配置**吗？

例如：长度超过 50 就自动隐藏其后的内容，如果没有的话，那打扰了，

Thanks！
