### ISSUE TITLE
在你的文章那里，需要省略的内容前面插入 `<!-- more -->` ，如下：

### ISSUE THREAD

**Issue by Wu-yikun** [korilin/hexo-theme-particle#5]
在你的文章那里，需要省略的内容前面插入 `<!-- more -->` ，如下：

```markdown

要显示的内容
OAuth 是用于......

<!-- more -->

要隐藏的内容

```

这在文档里面会成为一个注释，不会影响到你把文章迁移到其它地方。
Hexo 会把前面的内容单独抽出来，记得 more 两边最好都有一个空格。

如果还没能解决你可以重新打开这个 issue

_Originally posted by @korilin in https://github.com/korilin/hexo-theme-particle/issues/4#issuecomment-902604631_

那每一篇文章都需要如此设置吗？请问下有**全局配置**吗？

例如：长度超过 50 就自动隐藏其后的内容，如果没有的话，那打扰了，

Thanks！

**Comment by korilin** [comment]
目前没有这个配置，所以你需要每篇文章都插入 `<!-- more -->` 来定义摘要，这是 Hexo 原本就提供的一个功能。目前我并没有使用这个主题了，所以后续应该不会为这个功能添加全局配置。

**Comment by Wu-yikun** [comment]
ok



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月20日(周五) 晚上11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [korilin/hexo-theme-particle] 在你的文章那里，需要省略的内容前面插入 `<!-- more --&gt;` ，如下： (#5)




 
目前没有这个配置，所以你需要每篇文章都插入 <!-- more --&gt; 来定义摘要，这是 Hexo 原本就提供的一个功能。目前我并没有使用这个主题了，所以后续应该不会为这个功能添加全局配置。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
